version: '3.9'

services:
  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      - DOCKER\_INFLUXDB\_INIT\_MODE=setup
      - DOCKER\_INFLUXDB\_INIT\_USERNAME=admin
      - DOCKER\_INFLUXDB\_INIT\_PASSWORD=admin123456
      - DOCKER\_INFLUXDB\_INIT\_ORG=myorg
      - DOCKER\_INFLUXDB\_INIT\_BUCKET=mybucket
      - DOCKER\_INFLUXDB\_INIT\_ADMIN\_TOKEN=my-token-123
    volumes:
      - influxdb-data:/var/lib/influxdb

volumes:
  influxdb-data: